"""Claude Code hook templates + .claude.json writer (Phase 4 commit 4).

Two hooks ship as deterministic shell-script templates injected into
the leaf's working directory at session-spawn time:

  - PreToolUse: defence-in-depth allowed-tools gate. Uses
    AGENTPROVISION_ALLOWED_TOOLS env (whitespace-separated). NO network
    call — primary enforcement is server-side at the MCP boundary;
    this hook is a fast local gate that fails closed if the env is
    missing.

  - PostToolUse: fire-and-forget heartbeat to /api/v1/agents/internal/heartbeat
    with 2s timeout. Never blocks the tool, never errors out the leaf.

Both templates use ``STDIN=$(cat)`` (NOT ``read -r STDIN``) and
``jq -r '.tool_name // ""'`` (NOT ``.tool_input.tool_name``). Per
design §9.2 + Phase 3 review I-A and I-B: the prior draft of these
templates would have made TOOL="" always, permanently disabling the
PreToolUse gate.

The .claude.json writer creates the file with mode 0600 (SR-4) so a
co-tenant on the same workspace pod can't snoop the agent_token.

Idempotent — safe to re-invoke at every session spawn.
"""
from __future__ import annotations

import json
import os
import stat
from pathlib import Path


# ── Templates ────────────────────────────────────────────────────────────


_PRETOOLUSE_TEMPLATE = r'''#!/usr/bin/env bash
# Generated by code-worker; do not edit. AGENTPROVISION_ALLOWED_TOOLS
# is whitespace-separated. NO network call here — primary enforcement
# is server-side at the MCP boundary; this hook is a fast local gate
# that fails closed if the env is missing.
set -euo pipefail
STDIN=$(cat)
TOOL=$(jq -r '.tool_name // ""' <<<"$STDIN")
if [[ -z "${AGENTPROVISION_ALLOWED_TOOLS:-}" ]]; then
  exit 0   # no allowlist provided → trust server-side enforcement
fi
case " ${AGENTPROVISION_ALLOWED_TOOLS} " in
  *" ${TOOL} "*) exit 0 ;;
  *) echo "tool ${TOOL} not in agent.tool_groups allowlist" >&2; exit 2 ;;
esac
'''


_POSTTOOLUSE_TEMPLATE = r'''#!/usr/bin/env bash
# Generated by code-worker; do not edit. AGENTPROVISION_AGENT_TOKEN,
# AGENTPROVISION_TASK_ID, and AGENTPROVISION_API are injected into the
# subprocess env at spawn time and inherited by the hook process.
#
# Fail closed if AGENTPROVISION_API is unset — defaulting to the public
# tunnel hostname would leak heartbeats over the public internet from
# inside a worker pod if the env injection ever regresses (Phase 4
# review minor #8). The Cloudflare tunnel /internal/* block (#207)
# already 403s such traffic, but the better default is no default.
set -euo pipefail
STDIN=$(cat)
TOOL=$(jq -r '.tool_name // ""' <<<"$STDIN")
if [[ -z "${AGENTPROVISION_API:-}" ]]; then
  exit 0   # fail closed silent — hook never blocks the tool
fi
curl -fsS -m 2 -X POST \
  "${AGENTPROVISION_API}/api/v1/agents/internal/heartbeat" \
  -H "Authorization: Bearer ${AGENTPROVISION_AGENT_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "{\"task_id\":\"${AGENTPROVISION_TASK_ID}\",\"tool_name\":\"${TOOL}\",\"ts\":$(date +%s)}" \
  >/dev/null 2>&1 || true   # fire-and-forget — hook never blocks the tool
exit 0
'''


def render_pretooluse_hook() -> str:
    """Return the rendered PreToolUse hook text."""
    return _PRETOOLUSE_TEMPLATE


def render_posttooluse_hook() -> str:
    """Return the rendered PostToolUse hook text."""
    return _POSTTOOLUSE_TEMPLATE


# ── Writers ──────────────────────────────────────────────────────────────


def write_claude_hooks(workdir: Path) -> None:
    """Write both hook scripts under ``<workdir>/.claude/hooks/`` and
    register them in ``<workdir>/.claude/hooks/hooks.json``. chmod +x.

    Idempotent — overwrites cleanly on re-invocation.
    """
    workdir = Path(workdir)
    hooks_dir = workdir / ".claude" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    pre_path = hooks_dir / "pretooluse.sh"
    post_path = hooks_dir / "posttooluse.sh"

    pre_path.write_text(render_pretooluse_hook())
    post_path.write_text(render_posttooluse_hook())

    # chmod +x (preserve owner-rw, add owner+group+other-x)
    for p in (pre_path, post_path):
        current = p.stat().st_mode
        p.chmod(
            current
            | stat.S_IXUSR
            | stat.S_IXGRP
            | stat.S_IXOTH
        )

    hooks_json = hooks_dir / "hooks.json"
    hooks_json.write_text(
        json.dumps(
            {
                "hooks": [
                    {
                        "event": "PreToolUse",
                        "command": str(pre_path),
                    },
                    {
                        "event": "PostToolUse",
                        "command": str(post_path),
                    },
                ]
            },
            indent=2,
        )
    )


def write_claude_mcp_config(
    workdir: Path,
    agent_token: str,
    mcp_url: str,
) -> None:
    """Write ``<workdir>/.claude.json`` with the leaf's MCP config.

    The file is created with mode 0600 so a co-tenant process cannot
    read the agent_token (SR-4). Uses ``os.open(path, O_CREAT|O_WRONLY|
    O_TRUNC, 0o600)`` — this avoids the umask race that
    ``Path.write_text`` would have.

    Idempotent — re-invoking with a fresh token cleanly replaces the
    file (O_TRUNC + 0600).
    """
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)
    claude_json_path = workdir / ".claude.json"

    payload = {
        "mcpServers": {
            "agentprovision": {
                "type": "sse",
                "url": mcp_url,
                "headers": {
                    "Authorization": f"Bearer {agent_token}",
                },
            }
        }
    }
    body = json.dumps(payload, indent=2)

    fd = os.open(
        str(claude_json_path),
        os.O_CREAT | os.O_WRONLY | os.O_TRUNC,
        0o600,
    )
    try:
        os.write(fd, body.encode("utf-8"))
    finally:
        os.close(fd)
    # On filesystems where the umask intercepted the perm bits at
    # create time (rare for tmpfs / Mac APFS but possible on some
    # NFS), reassert mode after write.
    os.chmod(str(claude_json_path), 0o600)
