import os as _os
import time
import logging
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.base import BaseHTTPMiddleware
from slowapi import _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from app.core.rate_limit import limiter
from app.api.v1 import routes as v1_routes
from app.db.session import SessionLocal
from app.db.init_db import init_db
from app.core.logging import setup_logging, log_request

# Initialize structured logging
setup_logging(_os.environ.get("LOG_LEVEL", "INFO"))
logger = logging.getLogger(__name__)

db = SessionLocal()
try:
    init_db(db=db)
finally:
    db.close()

app = FastAPI(redirect_slashes=False)

# Rate limit handler
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)


class LoggingMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        start_time = time.time()
        response = await call_next(request)
        duration_ms = (time.time() - start_time) * 1000
        
        log_request(
            logger,
            request.method,
            request.url.path,
            response.status_code,
            duration_ms,
            extra={
                "client_ip": request.client.host,
                "user_agent": request.headers.get("user-agent"),
            }
        )
        return response


class TrailingSlashMiddleware(BaseHTTPMiddleware):
    """Strip trailing slashes before routing to avoid 307 redirects that lose POST bodies."""
    async def dispatch(self, request: Request, call_next):
        if request.url.path != "/" and request.url.path.endswith("/"):
            scope = request.scope
            scope["path"] = scope["path"].rstrip("/")
            if scope.get("raw_path"):
                scope["raw_path"] = scope["raw_path"].rstrip(b"/")
        return await call_next(request)


class ForceHTTPSRedirectMiddleware(BaseHTTPMiddleware):
    """Ensure any redirect generated by the app uses HTTPS when behind a proxy."""
    async def dispatch(self, request: Request, call_next):
        response = await call_next(request)
        if response.status_code in (301, 302, 307, 308):
            location = response.headers.get("location", "")
            if location.startswith("http://") and request.headers.get("x-forwarded-proto") == "https":
                response.headers["location"] = location.replace("http://", "https://", 1)
        return response


app.add_middleware(LoggingMiddleware)
app.add_middleware(TrailingSlashMiddleware)
app.add_middleware(ForceHTTPSRedirectMiddleware)

# Set up CORS middleware
import os as _os
_extra_origins = [o.strip() for o in _os.environ.get("CORS_EXTRA_ORIGINS", "").split(",") if o.strip()]
origins = [
    "https://agentprovision.com",
    "https://app.agentprovision.com",
    "https://www.agentprovision.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8002",
    "http://127.0.0.1:8002",
    "http://localhost:5173",  # Luna Client dev (Vite)
    "http://localhost:8009",  # Luna Client Docker
    "tauri://localhost",      # Luna Client Tauri (macOS/Windows)
    "tauri://*",              # Any Tauri scheme
    "https://tauri.localhost", # Mobile Tauri
    "https://luna.agentprovision.com",
] + _extra_origins

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(v1_routes.router, prefix="/api/v1")


@app.on_event("startup")
async def startup_skill_manager():
    """Scan and load all file-based skill definitions."""
    import logging as _logging
    from app.services.skill_manager import skill_manager
    skill_manager.scan()

    # Sync skills to DB registry + embeddings (background — don't block API startup)
    import threading
    def _sync_skills_background():
        from app.db.session import SessionLocal as _SessionLocal
        sync_db = _SessionLocal()
        try:
            from app.services.skill_registry_service import sync_skills_to_db
            sync_skills_to_db(sync_db)
            _logging.getLogger(__name__).info("Skill registry synced in background")
        except Exception as e:
            _logging.getLogger(__name__).warning(
                "Skill registry sync failed (pgvector may not be ready): %s", e
            )
        finally:
            sync_db.close()
    threading.Thread(target=_sync_skills_background, daemon=True).start()

    # Seed native workflow templates
    def _seed_workflow_templates():
        from app.db.session import SessionLocal as _SessionLocal
        tmpl_db = _SessionLocal()
        try:
            from app.services.workflow_templates import seed_native_templates
            count = seed_native_templates(tmpl_db)
            if count:
                _logging.getLogger(__name__).info("Seeded %d native workflow templates", count)
        except Exception as e:
            _logging.getLogger(__name__).debug("Workflow template seeding skipped: %s", e)
        finally:
            tmpl_db.close()
    threading.Thread(target=_seed_workflow_templates, daemon=True).start()

    # Pre-embed canonical intents for tier routing (light vs full model)
    def _init_intent_cache():
        try:
            from app.services.embedding_service import initialize_intent_embeddings
            initialize_intent_embeddings()
        except Exception as e:
            _logging.getLogger(__name__).warning("Intent embedding cache init failed: %s", e)
    threading.Thread(target=_init_intent_cache, daemon=True).start()


@app.on_event("startup")
async def startup_whatsapp():
    """Reconnect all enabled WhatsApp channel_accounts on startup."""
    try:
        from app.services.whatsapp_service import whatsapp_service
        await whatsapp_service.restore_connections()
    except Exception as e:
        import logging
        logging.getLogger(__name__).warning("WhatsApp startup skipped (neonize unavailable): %s", e)


@app.on_event("startup")
async def startup_whatsapp_readonly_auto_restore():
    """Auto-recover from the neonize 'attempt to write a readonly database'
    failure mode by hooking the whatsmeow.Client logger.

    History (4× over 30 hours, 2026-05-05 → 2026-05-06): the neonize
    SQLite session goes silently read-only after a few hours of uptime.
    Symptoms: incoming WhatsApp messages can't be decrypted/stored, no
    new chat_messages rows appear, the DB still shows status=connected.
    Manual fix is `docker compose restart api` which re-runs
    restore_connections() — neonize cleanly re-opens the session file.

    This hook attaches a logging Handler to the whatsmeow.Client logger.
    When a 'readonly database' record fires, it schedules a single
    restore_connections() call. Rate-limited to one trigger per 120s so
    a burst of decrypt failures doesn't cascade.
    """
    import asyncio
    import logging
    import time

    log = logging.getLogger(__name__)

    class _ReadonlyDetectingHandler(logging.Handler):
        def __init__(self, loop):
            super().__init__(level=logging.WARNING)
            self._last_trigger = 0.0
            self._loop = loop

        def emit(self, record):
            try:
                msg = record.getMessage()
            except Exception:
                return
            if "readonly database" not in msg:
                return
            now = time.monotonic()
            if now - self._last_trigger < 120.0:
                return  # cooldown — already recovering
            self._last_trigger = now
            log.warning(
                "WhatsApp readonly-DB pattern detected — auto-restoring "
                "connections (rate-limited: 120s cooldown)"
            )
            asyncio.run_coroutine_threadsafe(_do_restore(), self._loop)

    async def _do_restore():
        try:
            from app.services.whatsapp_service import whatsapp_service
            await whatsapp_service.restore_connections()
            log.info("WhatsApp auto-restore: completed successfully")
        except Exception as e:
            log.warning("WhatsApp auto-restore failed: %s", e)

    try:
        loop = asyncio.get_running_loop()
        handler = _ReadonlyDetectingHandler(loop)
        logging.getLogger("whatsmeow.Client").addHandler(handler)
        log.info("WhatsApp readonly-DB auto-restore handler installed")
    except Exception as e:
        log.warning("Failed to install WhatsApp auto-restore handler: %s", e)


@app.on_event("startup")
async def startup_teams_monitor_reconcile():
    """Re-spawn TeamsMonitorWorkflow for every enabled Teams account.

    Catches two scenarios:
      1. Tenants who enabled Teams before this workflow was deployed.
      2. API crashed between the channel-enable DB commit and the
         in-line ``start_workflow`` call in /teams/enable, leaving
         a "channel enabled, no monitor" zombie.

    Fire-and-forget via ``asyncio.create_task`` — the api becomes ready
    immediately and reconcile runs in the background. Was previously
    awaited inline; with 1000+ tenants the readiness probe would fail
    waiting on N sequential Temporal connects. PR-B follow-up to the
    2026-05-02 holistic review.

    Reconcile itself is bounded-concurrency (20 in flight) and uses
    a singleton Temporal client to avoid the per-call connect cost.
    """
    try:
        import asyncio
        from app.api.v1.channels import reconcile_teams_monitors

        async def _bg():
            try:
                await reconcile_teams_monitors()
            except Exception as e:
                import logging
                logging.getLogger(__name__).warning(
                    "Teams monitor reconcile (background) failed: %s", e,
                )

        # Fire-and-forget. Loop is the FastAPI startup loop; the task
        # runs alongside the request loop for the api lifetime.
        asyncio.create_task(_bg())
    except Exception as e:
        import logging
        logging.getLogger(__name__).warning(
            "Teams monitor reconcile skipped: %s", e,
        )


@app.on_event("startup")
async def startup_proactive_workflows():
    """Auto-start long-running Temporal workflows for all active tenants.

    Launches per-tenant dynamic workflow instances of:
      - Autonomous Learning (nightly dream/RL cycle + morning report)
      - Inbox Monitor (Gmail/Calendar monitoring every 15 min)
      - Competitor Monitor (competitor intelligence, daily)

    Uses workflow_id_reuse_policy to skip tenants that already have a
    running instance (idempotent on restart).
    """
    import asyncio
    import logging as _logging
    from app.db.session import SessionLocal as _SL

    logger = _logging.getLogger(__name__)

    async def _launch():
        # Give Temporal a few seconds to be ready
        await asyncio.sleep(5)
        try:
            from app.services.dynamic_workflow_launcher import start_dynamic_workflow_by_name

            db = _SL()
            try:
                from sqlalchemy import text
                tenants = db.execute(text(
                    "SELECT id::text FROM tenants"
                )).fetchall()
            finally:
                db.close()

            launched = 0
            for (tid,) in tenants:
                # Autonomous learning (nightly)
                try:
                    await start_dynamic_workflow_by_name("Autonomous Learning", tid)
                    launched += 1
                except Exception:
                    pass  # already running or template not found

                # Inbox monitor (every 15 min)
                try:
                    await start_dynamic_workflow_by_name("Inbox Monitor", tid)
                    launched += 1
                except Exception:
                    pass

                # Competitor monitor (daily)
                try:
                    await start_dynamic_workflow_by_name("Competitor Monitor", tid)
                    launched += 1
                except Exception:
                    pass

            logger.info("Proactive workflows: launched %d new instances for %d tenants", launched, len(tenants))
        except Exception as e:
            logger.warning("Proactive workflow auto-start failed (Temporal may not be ready): %s", e)

    asyncio.ensure_future(_launch())


@app.on_event("shutdown")
async def shutdown_whatsapp():
    """Gracefully disconnect all neonize clients."""
    try:
        from app.services.whatsapp_service import whatsapp_service
        await whatsapp_service.shutdown()
    except Exception:
        pass
