# Code Agent E2E test - branch naming verification
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.base import BaseHTTPMiddleware
from app.api.v1 import routes as v1_routes
from app.db.session import SessionLocal
from app.db.init_db import init_db

init_db(db=SessionLocal())

app = FastAPI()


class ForceHTTPSRedirectMiddleware(BaseHTTPMiddleware):
    """Ensure any redirect generated by the app uses HTTPS when behind a proxy."""
    async def dispatch(self, request: Request, call_next):
        response = await call_next(request)
        if response.status_code in (301, 302, 307, 308):
            location = response.headers.get("location", "")
            if location.startswith("http://") and request.headers.get("x-forwarded-proto") == "https":
                response.headers["location"] = location.replace("http://", "https://", 1)
        return response


app.add_middleware(ForceHTTPSRedirectMiddleware)

# Set up CORS middleware
origins = [
    "https://servicetsunami.com",
    "https://agentprovision.com",
    "https://www.agentprovision.com",
    "http://localhost:3000", # For local development
    "http://127.0.0.1:3000", # For local development
    "http://localhost:8002", # Docker web service
    "http://127.0.0.1:8002", # Docker web service
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(v1_routes.router, prefix="/api/v1")


@app.on_event("startup")
async def startup_whatsapp():
    """Reconnect all enabled WhatsApp channel_accounts on startup."""
    from app.services.whatsapp_service import whatsapp_service
    await whatsapp_service.restore_connections()


@app.on_event("shutdown")
async def shutdown_whatsapp():
    """Gracefully disconnect all neonize clients."""
    from app.services.whatsapp_service import whatsapp_service
    await whatsapp_service.shutdown()
