from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.base import BaseHTTPMiddleware
from app.api.v1 import routes as v1_routes
from app.db.session import SessionLocal
from app.db.init_db import init_db

init_db(db=SessionLocal())

app = FastAPI()


class ForceHTTPSRedirectMiddleware(BaseHTTPMiddleware):
    """Ensure any redirect generated by the app uses HTTPS when behind a proxy."""
    async def dispatch(self, request: Request, call_next):
        response = await call_next(request)
        if response.status_code in (301, 302, 307, 308):
            location = response.headers.get("location", "")
            if location.startswith("http://") and request.headers.get("x-forwarded-proto") == "https":
                response.headers["location"] = location.replace("http://", "https://", 1)
        return response


app.add_middleware(ForceHTTPSRedirectMiddleware)

# Set up CORS middleware
import os as _os
_extra_origins = [o.strip() for o in _os.environ.get("CORS_EXTRA_ORIGINS", "").split(",") if o.strip()]
origins = [
    "https://agentprovision.com",
    "https://app.agentprovision.com",
    "https://servicetsunami.com",
    "https://www.agentprovision.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8002",
    "http://127.0.0.1:8002",
    "http://localhost:5173",  # Luna Client dev (Vite)
    "http://localhost:8009",  # Luna Client Docker
    "tauri://localhost",      # Luna Client Tauri (macOS/iOS/Android)
    "https://luna.servicetsunami.com",
] + _extra_origins

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(v1_routes.router, prefix="/api/v1")


@app.on_event("startup")
async def startup_skill_manager():
    """Scan and load all file-based skill definitions."""
    import logging as _logging
    from app.services.skill_manager import skill_manager
    skill_manager.scan()

    # Sync skills to DB registry + embeddings (background — don't block API startup)
    import threading
    def _sync_skills_background():
        try:
            from app.services.skill_registry_service import sync_skills_to_db
            from app.db.session import SessionLocal as _SessionLocal
            sync_db = _SessionLocal()
            sync_skills_to_db(sync_db)
            sync_db.close()
            _logging.getLogger(__name__).info("Skill registry synced in background")
        except Exception as e:
            _logging.getLogger(__name__).warning(
                "Skill registry sync failed (pgvector may not be ready): %s", e
            )
    threading.Thread(target=_sync_skills_background, daemon=True).start()

    # Seed native workflow templates
    def _seed_workflow_templates():
        try:
            from app.services.workflow_templates import seed_native_templates
            from app.db.session import SessionLocal as _SessionLocal
            tmpl_db = _SessionLocal()
            count = seed_native_templates(tmpl_db)
            tmpl_db.close()
            if count:
                _logging.getLogger(__name__).info("Seeded %d native workflow templates", count)
        except Exception as e:
            _logging.getLogger(__name__).debug("Workflow template seeding skipped: %s", e)
    threading.Thread(target=_seed_workflow_templates, daemon=True).start()


@app.on_event("startup")
async def startup_whatsapp():
    """Reconnect all enabled WhatsApp channel_accounts on startup."""
    from app.services.whatsapp_service import whatsapp_service
    await whatsapp_service.restore_connections()


@app.on_event("startup")
async def startup_proactive_workflows():
    """Auto-start long-running Temporal workflows for all active tenants.

    Launches per-tenant instances of:
      - AutonomousLearningWorkflow (nightly dream/RL cycle + morning report)
      - InboxMonitorWorkflow (Gmail/Calendar monitoring every 15 min)
      - CompetitorMonitorWorkflow (competitor intelligence, daily)

    Uses workflow_id_reuse_policy to skip tenants that already have a
    running instance (idempotent on restart).
    """
    import asyncio
    import logging as _logging
    from app.db.session import SessionLocal as _SL

    logger = _logging.getLogger(__name__)

    async def _launch():
        # Give Temporal a few seconds to be ready
        await asyncio.sleep(5)
        try:
            from temporalio.client import Client
            from temporalio.common import WorkflowIDReusePolicy
            from app.workflows.autonomous_learning import AutonomousLearningWorkflow
            from app.workflows.inbox_monitor import InboxMonitorWorkflow
            from app.workflows.competitor_monitor import CompetitorMonitorWorkflow

            client = await Client.connect("temporal:7233")
            db = _SL()
            try:
                from sqlalchemy import text
                tenants = db.execute(text(
                    "SELECT id::text FROM tenants"
                )).fetchall()
            finally:
                db.close()

            launched = 0
            for (tid,) in tenants:
                # Autonomous learning (nightly)
                try:
                    await client.start_workflow(
                        AutonomousLearningWorkflow.run,
                        tid,
                        id=f"autonomous-learning-{tid}",
                        task_queue="servicetsunami-orchestration",
                        id_reuse_policy=WorkflowIDReusePolicy.REJECT_DUPLICATE,
                    )
                    launched += 1
                except Exception:
                    pass  # already running

                # Inbox monitor (every 15 min)
                try:
                    await client.start_workflow(
                        InboxMonitorWorkflow.run,
                        tid,
                        id=f"inbox-monitor-{tid}",
                        task_queue="servicetsunami-orchestration",
                        id_reuse_policy=WorkflowIDReusePolicy.REJECT_DUPLICATE,
                    )
                    launched += 1
                except Exception:
                    pass

                # Competitor monitor (daily)
                try:
                    await client.start_workflow(
                        CompetitorMonitorWorkflow.run,
                        tid,
                        id=f"competitor-monitor-{tid}",
                        task_queue="servicetsunami-orchestration",
                        id_reuse_policy=WorkflowIDReusePolicy.REJECT_DUPLICATE,
                    )
                    launched += 1
                except Exception:
                    pass

            logger.info("Proactive workflows: launched %d new instances for %d tenants", launched, len(tenants))
        except Exception as e:
            logger.warning("Proactive workflow auto-start failed (Temporal may not be ready): %s", e)

    asyncio.ensure_future(_launch())


@app.on_event("shutdown")
async def shutdown_whatsapp():
    """Gracefully disconnect all neonize clients."""
    from app.services.whatsapp_service import whatsapp_service
    await whatsapp_service.shutdown()
