import React, { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import {
  Alert, Badge, Button, Card, Col, Dropdown, Form,
  InputGroup, Modal, Nav, Row, Spinner,
} from 'react-bootstrap';
import {
  FaCode, FaCodeBranch, FaChevronDown, FaChevronUp, FaCopy, FaDownload,
  FaEdit, FaEllipsisV, FaExclamationTriangle, FaFileAlt, FaGithub,
  FaHistory, FaPlay, FaPlug, FaPlus, FaRocket, FaSearch, FaTerminal,
  FaTimes, FaTrash,
} from 'react-icons/fa';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useTranslation } from 'react-i18next';
import Layout from '../components/Layout';
import {
  getFileSkills, createFileSkill, updateFileSkill, forkFileSkill,
  deleteFileSkill, executeFileSkill, getSkillVersions, importFromGithub,
  getMcpManifest, exportSkill,
} from '../services/skills';
import './SkillsPage.css';

// Category accent colors — muted to match the Agent Fleet palette. Used for the
// category badge on each card. The chip row (above the grid) is driven by the
// shared .skills-chip class in SkillsPage.css — not by these colors — so all
// inactive chips read as one family.
const CATEGORY_COLORS = {
  sales: '#3b9d86',        // teal (Fleet accent)
  marketing: '#c2650c',    // amber
  data: '#2b7de9',         // primary blue
  coding: '#5b6fb3',       // muted indigo
  communication: '#8b5cf6',// purple
  automation: '#c27803',   // gold
  general: '#64748b',      // slate
  'auto-generated': '#94a3b8',
};

const CATEGORIES = ['all', 'sales', 'marketing', 'data', 'coding', 'communication', 'automation', 'general'];

// Noisy import artifacts (failed CLI tool-call timeouts) — filtered from Native tab
const AUTO_GENERATED_DESCRIPTION_PATTERN = /response timeout pattern/i;
const isAutoGenerated = (s) =>
  s.category === 'auto-generated' ||
  (s.description && AUTO_GENERATED_DESCRIPTION_PATTERN.test(s.description));

const ENGINE_ICONS = { python: FaCode, shell: FaTerminal, markdown: FaFileAlt };

const ENGINE_DEFAULTS = {
  python: 'def execute(inputs):\n    # Your skill logic here\n    return {"result": "done"}',
  shell: '#!/bin/bash\n# Inputs are available as SKILL_INPUT_<NAME> env vars\necho "Hello from skill"\n',
  markdown: '# Prompt Template\n\nUse {{input_name}} for placeholders.\n\nInstructions for the agent go here.\n',
};

const inputStyle = {
  background: 'var(--surface-contrast, rgba(0,0,0,0.2))',
  border: '1px solid var(--color-border)',
  color: 'var(--color-foreground)',
  borderRadius: 8,
};

const modalSectionStyle = { background: 'var(--surface-elevated)' };

const EMPTY_SKILL = { name: '', description: '', engine: 'python', category: 'general', auto_trigger: '', tags: '', chain_to: [], script: ENGINE_DEFAULTS.python, inputs: [] };

const SkillsPage = () => {
  const { t } = useTranslation('skills');
  const [skills, setSkills] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(null);
  const [activeTab, setActiveTab] = useState('native');
  const [activeCategory, setActiveCategory] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [showCreate, setShowCreate] = useState(false);
  const [showImport, setShowImport] = useState(false);
  const [executeSkill, setExecuteSkill] = useState(null);
  const [executeInputs, setExecuteInputs] = useState({});
  const [executing, setExecuting] = useState(false);
  const [executeResult, setExecuteResult] = useState(null);
  const [editSkill, setEditSkill] = useState(null);
  const [expandedSkill, setExpandedSkill] = useState(null);
  const [creating, setCreating] = useState(false);
  const [importUrl, setImportUrl] = useState('');
  const [importing, setImporting] = useState(false);
  const [newSkill, setNewSkill] = useState({ ...EMPTY_SKILL });
  const [showMcpConnect, setShowMcpConnect] = useState(false);
  const [mcpManifest, setMcpManifest] = useState(null);
  const [mcpLoading, setMcpLoading] = useState(false);
  const [copied, setCopied] = useState(null);
  const [formErrors, setFormErrors] = useState({});
  const debounceRef = useRef(null);

  const fetchSkills = useCallback(async (search) => {
    try {
      setLoading(true);
      const params = {};
      if (search && search.length > 2) params.search = search;
      const response = await getFileSkills(params);
      setSkills(response.data || []);
    } catch (err) {
      console.error('Error fetching skills:', err);
      setError(t('errors.load'));
    } finally {
      setLoading(false);
    }
  }, [t]);

  useEffect(() => { fetchSkills(); }, [fetchSkills]);

  useEffect(() => {
    if (debounceRef.current) clearTimeout(debounceRef.current);
    if (searchQuery.length > 2) {
      debounceRef.current = setTimeout(() => fetchSkills(searchQuery), 300);
    }
    return () => { if (debounceRef.current) clearTimeout(debounceRef.current); };
  }, [searchQuery, fetchSkills]);

  const filtered = skills
    .filter(s => activeTab === 'native' ? s.tier === 'native' : activeTab === 'my' ? s.tier === 'custom' : s.tier === 'community')
    // Hide auto-generated import artifacts from Native tab. Still visible in My/Community
    // if a tenant deliberately authored them.
    .filter(s => activeTab !== 'native' || !isAutoGenerated(s))
    .filter(s => activeCategory === 'all' || s.category === activeCategory)
    .filter(s => !searchQuery || s.name.toLowerCase().includes(searchQuery.toLowerCase()) || (s.description || '').toLowerCase().includes(searchQuery.toLowerCase()));

  const flash = (setter, msg, ms = 4000) => { setter(msg); setTimeout(() => setter(null), ms); };

  // --- Execute ---
  const handleOpenExecute = (skill) => {
    setExecuteSkill(skill);
    const defaults = {};
    (skill.inputs || []).forEach(inp => { defaults[inp.name] = ''; });
    setExecuteInputs(defaults);
    setExecuteResult(null);
  };

  const handleExecute = async () => {
    if (!executeSkill) return;
    try {
      setExecuting(true);
      setExecuteResult(null);
      const response = await executeFileSkill(executeSkill.name, executeInputs);
      setExecuteResult({ success: true, data: response.data });
    } catch (err) {
      setExecuteResult({ success: false, error: err.response?.data?.detail || t('errors.execute') });
    } finally {
      setExecuting(false);
    }
  };

  // --- Create / Edit ---
  const openCreate = () => {
    setEditSkill(null);
    setNewSkill({ ...EMPTY_SKILL });
    setShowCreate(true);
  };

  const openEdit = (skill) => {
    setEditSkill(skill);
    setNewSkill({
      name: skill.name, description: skill.description || '', engine: skill.engine || 'python',
      category: skill.category || 'general', auto_trigger: skill.auto_trigger || '',
      tags: (skill.tags || []).join(', '), chain_to: skill.chain_to || [],
      script: skill.script || ENGINE_DEFAULTS[skill.engine || 'python'],
      inputs: skill.inputs || [],
    });
    setShowCreate(true);
  };

  // --- Validation ---
  // Python skills must expose an `execute(inputs)` function. Markdown skills must
  // reference only declared inputs via `{{name}}`. Catch these client-side to give
  // users fast feedback; the API re-validates on save as the source of truth.
  const validateSkill = (skill) => {
    const errors = {};
    if (!skill.name.trim()) errors.name = t('validation.nameRequired');

    const inputs = (skill.inputs || []).filter(i => i.name.trim());
    const inputNames = new Set(inputs.map(i => i.name.trim()));
    const script = skill.script || '';

    if (skill.engine === 'python') {
      if (!/(^|\n)\s*def\s+execute\s*\(\s*[a-zA-Z_][\w]*\s*\)/.test(script)) {
        errors.script = t('validation.pythonSignature');
      }
    } else if (skill.engine === 'markdown') {
      const refs = [...script.matchAll(/\{\{\s*([a-zA-Z_][\w]*)\s*\}\}/g)].map(m => m[1]);
      const missing = refs.filter(n => !inputNames.has(n));
      if (missing.length > 0) {
        errors.script = t('validation.markdownMissingInputs', { vars: [...new Set(missing)].join(', ') });
      }
    }
    return errors;
  };

  const handleSaveSkill = async () => {
    const errors = validateSkill(newSkill);
    setFormErrors(errors);
    if (Object.keys(errors).length > 0) return;

    try {
      setCreating(true);
      const payload = {
        name: newSkill.name.trim(), description: newSkill.description.trim(),
        engine: newSkill.engine, category: newSkill.category,
        auto_trigger: newSkill.auto_trigger.trim() || null,
        tags: newSkill.tags ? newSkill.tags.split(',').map(t => t.trim()).filter(Boolean) : [],
        chain_to: newSkill.chain_to, script: newSkill.script,
        inputs: newSkill.inputs.filter(i => i.name.trim()),
      };
      if (editSkill) {
        await updateFileSkill(editSkill.slug, payload);
        flash(setSuccess, t('updated'));
      } else {
        await createFileSkill(payload);
        flash(setSuccess, t('skillCreated'));
      }
      setShowCreate(false);
      setNewSkill({ ...EMPTY_SKILL });
      await fetchSkills();
    } catch (err) {
      flash(setError, err.response?.data?.detail || (editSkill ? t('errors.update') : t('errors.create')), 5000);
    } finally {
      setCreating(false);
    }
  };

  // --- Fork / Delete ---
  const handleFork = async (skill) => {
    try {
      await forkFileSkill(skill.slug);
      flash(setSuccess, t('forked'));
      await fetchSkills();
    } catch (err) {
      flash(setError, err.response?.data?.detail || t('errors.fork'), 5000);
    }
  };

  const handleDelete = async (skill) => {
    if (!window.confirm(`Delete "${skill.name}"?`)) return;
    try {
      await deleteFileSkill(skill.slug);
      flash(setSuccess, t('deleted'));
      await fetchSkills();
    } catch (err) {
      flash(setError, err.response?.data?.detail || t('errors.delete'), 5000);
    }
  };

  // --- Import ---
  const handleImportGithub = async () => {
    if (!importUrl.trim()) return;
    try {
      setImporting(true);
      await importFromGithub(importUrl.trim());
      flash(setSuccess, t('imported'));
      setShowImport(false);
      setImportUrl('');
      await fetchSkills();
    } catch (err) {
      flash(setError, err.response?.data?.detail || t('errors.import'), 5000);
    } finally {
      setImporting(false);
    }
  };

  // --- MCP connect modal ---
  const openMcpConnect = async () => {
    setShowMcpConnect(true);
    if (mcpManifest) return;
    try {
      setMcpLoading(true);
      const resp = await getMcpManifest();
      setMcpManifest(resp.data);
    } catch (err) {
      flash(setError, err.response?.data?.detail || t('errors.load'), 5000);
    } finally {
      setMcpLoading(false);
    }
  };

  // navigator.clipboard is gated on secure contexts. On HTTP/localhost dev and
  // older browsers it's undefined — fall back to the legacy textarea/execCommand
  // trick so the Copy buttons never silently fail.
  const copyToClipboard = (text, key) => {
    const mark = () => { setCopied(key); setTimeout(() => setCopied(null), 1500); };
    if (navigator.clipboard && window.isSecureContext) {
      navigator.clipboard.writeText(text).then(mark).catch(() => fallback());
      return;
    }
    fallback();
    function fallback() {
      try {
        const ta = document.createElement('textarea');
        ta.value = text;
        ta.style.position = 'fixed';
        ta.style.opacity = '0';
        document.body.appendChild(ta);
        ta.select();
        document.execCommand('copy');
        document.body.removeChild(ta);
        mark();
      } catch {
        flash(setError, 'Copy failed — please select and copy manually', 3000);
      }
    }
  };

  // Single source of truth for the MCP endpoint the modal advertises. Used by
  // all three snippets and the clipboard buttons so they can never drift.
  // The current user's JWT lives under localStorage 'user' (not 'authToken') —
  // see apps/web/src/services/api.js request interceptor.
  const mcpServerUrl = mcpManifest?.server_url || `${window.location.origin}/api/v1/mcp`;
  const mcpTenantId = mcpManifest?.tenant_id || '<your-tenant-id>';
  const storedUser = (() => { try { return JSON.parse(localStorage.getItem('user') || 'null'); } catch { return null; } })();
  const mcpToken = storedUser?.access_token || '<your-api-token>';

  const mcpConfigs = useMemo(() => ({
    claude: {
      mcpServers: {
        agentprovision: {
          transport: 'http',
          url: mcpServerUrl,
          headers: {
            Authorization: `Bearer ${mcpToken}`,
            'X-Tenant-Id': mcpTenantId,
          },
        },
      },
    },
    gemini: {
      mcp: {
        servers: {
          agentprovision: {
            url: mcpServerUrl,
            headers: {
              Authorization: `Bearer ${mcpToken}`,
              'X-Tenant-Id': mcpTenantId,
            },
          },
        },
      },
    },
    copilot: {
      'github.copilot.chat.mcp.servers': {
        agentprovision: {
          url: mcpServerUrl,
          headers: {
            Authorization: `Bearer ${mcpToken}`,
            'X-Tenant-Id': mcpTenantId,
          },
        },
      },
    },
  }), [mcpServerUrl, mcpTenantId, mcpToken]);

  const handleExport = async (skill, format) => {
    try {
      const resp = await exportSkill(skill.slug, format);
      const ext = format === 'openai' ? 'json' : 'md';
      const filename = `${skill.slug || skill.name}.${format}.${ext}`;
      const contentType = format === 'openai' ? 'application/json' : 'text/markdown';
      const body = typeof resp.data === 'string' ? resp.data : JSON.stringify(resp.data, null, 2);
      const blob = new Blob([body], { type: contentType });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = filename;
      document.body.appendChild(a); a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      flash(setError, err.response?.data?.detail || 'Export failed', 3000);
    }
  };

  // --- Input builder helpers ---
  const handleAddInput = () => setNewSkill({ ...newSkill, inputs: [...newSkill.inputs, { name: '', type: 'string', description: '', required: false }] });
  const handleRemoveInput = (i) => setNewSkill({ ...newSkill, inputs: newSkill.inputs.filter((_, idx) => idx !== i) });
  const handleInputChange = (i, field, val) => { const u = [...newSkill.inputs]; u[i] = { ...u[i], [field]: val }; setNewSkill({ ...newSkill, inputs: u }); };

  // --- Skill Card ---
  const SkillCard = ({ skill }) => {
    const EngineIcon = ENGINE_ICONS[skill.engine] || FaCode;
    const isExpanded = expandedSkill === skill.slug;
    const catColor = CATEGORY_COLORS[skill.category] || CATEGORY_COLORS.general;

    return (
      <Card className="skill-card">
        <div className="skill-card-body" onClick={() => setExpandedSkill(isExpanded ? null : skill.slug)}>
          {/* Header row */}
          <div className="d-flex align-items-start justify-content-between mb-2">
            <div className="d-flex align-items-center gap-2" style={{ minWidth: 0, flex: 1 }}>
              <div className="skill-icon">
                <EngineIcon size={16} />
              </div>
              <h6 className="skill-card-title">{skill.name}</h6>
            </div>
            <div className="d-flex align-items-center gap-1" style={{ flexShrink: 0 }}>
              <span className="skill-engine-badge">{skill.engine}</span>
              {skill.version && <span className="skill-version-badge">{t('version', { version: skill.version })}</span>}
            </div>
          </div>

          {/* Category + Tier badges — plain spans so Bootstrap can't override the background */}
          <div className="d-flex align-items-center gap-2 mb-2 flex-wrap">
            <span
              className="skill-category-badge"
              style={{ background: catColor + '1f', color: catColor, borderColor: catColor + '3d' }}
            >
              {t(`categories.${skill.category}`, { defaultValue: skill.category })}
            </span>
            <span className={`skill-tier-badge skill-tier-${skill.tier || 'native'}`}>
              {t(`tabs.${skill.tier === 'custom' ? 'mySkills' : skill.tier}`)}
            </span>
          </div>

          {/* Description — plain-text clamp when collapsed; full markdown when expanded.
              Many skills embed rubric tables and sub-headings in their descriptions;
              rendering as text-only at a glance but with full fidelity on expand keeps
              the grid skimmable. */}
          {skill.description && (
            isExpanded ? (
              <div className="skill-description-full mb-2">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{skill.description}</ReactMarkdown>
              </div>
            ) : (
              <p className="skill-description mb-2">{skill.description}</p>
            )
          )}

          {/* Auto-trigger / Chain indicators */}
          {skill.auto_trigger && <div className="skill-auto-trigger"><FaRocket size={10} />Auto-triggers on: {skill.auto_trigger}</div>}
          {skill.chain_to && skill.chain_to.length > 0 && <div className="skill-chain-to"><FaCodeBranch size={10} />Chains to: {skill.chain_to.join(', ')}</div>}

          {/* Expanded details */}
          {isExpanded && (
            <div className="skill-expanded-section">
              {skill.inputs && skill.inputs.length > 0 && (
                <div className="mb-2">
                  <div className="skill-expanded-heading">{t('inputs')}</div>
                  {skill.inputs.map(inp => (
                    <div key={inp.name} className="skill-input-row">
                      <code className="skill-input-name">{inp.name}</code>
                      <span className="skill-input-type">({inp.type || 'string'})</span>
                      <span className={inp.required ? 'skill-input-required' : 'skill-input-optional'}>
                        {inp.required ? t('required') : t('optional')}
                      </span>
                    </div>
                  ))}
                </div>
              )}
              {skill.sub_prompts && skill.sub_prompts.length > 0 && (
                <div className="mb-2">
                  <div className="skill-expanded-heading">Sub-prompts</div>
                  {skill.sub_prompts.map((sp, i) => <div key={i} className="skill-input-type">- {sp.name || sp}</div>)}
                </div>
              )}
              {skill.tags && skill.tags.length > 0 && (
                <div className="d-flex flex-wrap">
                  {skill.tags.map(tag => <span key={tag} className="skill-tag">#{tag}</span>)}
                </div>
              )}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="skill-card-footer">
          <Button className="skill-try-btn" size="sm" onClick={e => { e.stopPropagation(); handleOpenExecute(skill); }}>
            <FaPlay className="me-1" size={10} /> {t('tryIt')}
          </Button>
          <div className="d-flex align-items-center gap-1">
            <span className="skill-action-icon" onClick={e => { e.stopPropagation(); setExpandedSkill(isExpanded ? null : skill.slug); }}>
              {isExpanded ? <FaChevronUp size={12} /> : <FaChevronDown size={12} />}
            </span>
            <Dropdown onClick={e => e.stopPropagation()}>
              <Dropdown.Toggle as="span" className="skill-action-icon"><FaEllipsisV size={12} /></Dropdown.Toggle>
              <Dropdown.Menu align="end" style={{ background: 'var(--surface-elevated)', border: '1px solid var(--color-border)', borderRadius: 10, minWidth: 180 }}>
                {skill.tier === 'native' && (
                  <>
                    <Dropdown.Item onClick={() => handleFork(skill)}><FaCodeBranch className="me-2" size={12} />{t('actions.fork')}</Dropdown.Item>
                    <Dropdown.Item onClick={() => setExpandedSkill(skill.slug)}><FaCode className="me-2" size={12} />{t('viewSource')}</Dropdown.Item>
                  </>
                )}
                {skill.tier === 'custom' && (
                  <>
                    <Dropdown.Item onClick={() => openEdit(skill)}><FaEdit className="me-2" size={12} />{t('actions.edit')}</Dropdown.Item>
                    <Dropdown.Item onClick={() => {}}><FaHistory className="me-2" size={12} />{t('actions.versions')}</Dropdown.Item>
                    <Dropdown.Divider />
                    <Dropdown.Item onClick={() => handleDelete(skill)} className="text-danger"><FaTrash className="me-2" size={12} />{t('actions.delete')}</Dropdown.Item>
                  </>
                )}
                {skill.tier === 'community' && (
                  <>
                    <Dropdown.Item onClick={() => handleFork(skill)}><FaCodeBranch className="me-2" size={12} />{t('actions.fork')}</Dropdown.Item>
                    <Dropdown.Item onClick={() => setExpandedSkill(skill.slug)}><FaCode className="me-2" size={12} />{t('viewSource')}</Dropdown.Item>
                    {skill.source_repo && <Dropdown.Item href={skill.source_repo} target="_blank" rel="noopener noreferrer"><FaGithub className="me-2" size={12} />{t('actions.viewGithub')}</Dropdown.Item>}
                  </>
                )}
                <Dropdown.Divider />
                <Dropdown.Header style={{ fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.5px' }}>{t('actions.exportAs')}</Dropdown.Header>
                <Dropdown.Item onClick={() => handleExport(skill, 'superpowers')}><FaDownload className="me-2" size={11} />Superpowers (SKILL.md)</Dropdown.Item>
                <Dropdown.Item onClick={() => handleExport(skill, 'gws')}><FaDownload className="me-2" size={11} />GWS (SKILL.md)</Dropdown.Item>
                <Dropdown.Item onClick={() => handleExport(skill, 'openai')}><FaDownload className="me-2" size={11} />OpenAI function (JSON)</Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
          </div>
        </div>
      </Card>
    );
  };

  return (
    <Layout>
      <div className="skills-page">
        {/* Header */}
        <div className="skills-page-header">
          <div className="skills-identity">
            <div className="skills-page-icon">
              <FaRocket size={22} />
            </div>
            <div>
              <h2 className="skills-page-title">{t('title')}</h2>
              <p className="skills-page-subtitle">{t('subtitle')}</p>
            </div>
          </div>
          <div className="d-flex gap-2 flex-wrap">
            <Button variant="outline-primary" onClick={openMcpConnect} style={{ borderRadius: 8 }} title={t('mcp.connectExternal')}>
              <FaPlug className="me-2" size={13} />{t('mcp.connectExternal')}
            </Button>
            <Button variant="outline-secondary" onClick={() => setShowImport(true)} style={{ borderRadius: 8 }}>
              <FaGithub className="me-2" size={14} />{t('actions.import')}
            </Button>
            <Button variant="primary" onClick={openCreate} style={{ borderRadius: 8 }}>
              <FaPlus className="me-2" size={12} />{t('createSkill')}
            </Button>
          </div>
        </div>

        {/* Search */}
        <InputGroup className="skills-search-wrapper">
          <InputGroup.Text style={{ borderTopRightRadius: 0, borderBottomRightRadius: 0 }}>
            <FaSearch size={14} />
          </InputGroup.Text>
          <Form.Control
            placeholder={t('search.placeholder')}
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            style={{ borderTopLeftRadius: 0, borderBottomLeftRadius: 0 }}
          />
        </InputGroup>

        {/* Tabs — plain divs, not react-bootstrap Nav.Pills, so Bootstrap's .nav-link.active
            doesn't stomp our palette. */}
        <div className="skills-tabs">
          {['native', 'my', 'community'].map(tab => (
            <div
              key={tab}
              role="button"
              className={`skills-tab ${activeTab === tab ? 'active' : ''}`}
              onClick={() => setActiveTab(tab)}
            >
              {tab === 'my' ? t('tabs.mySkills') : t(`tabs.${tab}`)}
            </div>
          ))}
        </div>

        {/* Category chips — plain spans so Bootstrap's .badge (bg-primary default) can't
            override the tinted inactive state that made them all read as "selected". */}
        <div className="skills-category-chips">
          {CATEGORIES.map(cat => (
            <span
              key={cat}
              role="button"
              className={`skills-chip ${activeCategory === cat ? 'active' : ''}`}
              onClick={() => setActiveCategory(cat)}
            >
              {t(`categories.${cat}`)}
            </span>
          ))}
        </div>

        {/* Alerts */}
        {error && <Alert variant="danger" onClose={() => setError(null)} dismissible className="mb-3">{error}</Alert>}
        {success && <Alert variant="success" onClose={() => setSuccess(null)} dismissible className="mb-3">{success}</Alert>}

        {/* Loading */}
        {loading && (
          <div className="text-center py-5">
            <Spinner animation="border" variant="primary" />
            <p className="text-muted mt-3 mb-0">{t('loading')}</p>
          </div>
        )}

        {/* Empty */}
        {!loading && filtered.length === 0 && (
          <Card className="skill-card text-center py-5">
            <Card.Body>
              <FaRocket size={48} className="mb-3" style={{ color: 'rgba(45, 65, 90, 0.35)' }} />
              <h5 style={{ color: '#1a2b3c' }}>{t('noSkills')}</h5>
              <p className="mb-3" style={{ color: 'rgba(45, 65, 90, 0.65)' }}>{t('noSkillsDesc')}</p>
              <Button variant="primary" onClick={openCreate}><FaPlus className="me-2" size={12} />{t('createSkill')}</Button>
            </Card.Body>
          </Card>
        )}

        {/* Grid */}
        {!loading && filtered.length > 0 && (
          <>
            <div className="skills-count">
              {filtered.length} {t('totalSkills')}
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(350px, 1fr))', gap: '1.25rem' }}>
              {filtered.map(skill => <SkillCard key={skill.slug || skill.name} skill={skill} />)}
            </div>
          </>
        )}

        {/* ── Execute Modal ── */}
        <Modal show={!!executeSkill} onHide={() => { setExecuteSkill(null); setExecuteResult(null); }} size="lg" centered>
          <Modal.Header closeButton style={{ ...modalSectionStyle, borderBottom: '1px solid var(--color-border)' }}>
            <Modal.Title style={{ fontSize: '1.1rem' }}><FaPlay className="me-2" size={14} />{t('execute.title')}: {executeSkill?.name}</Modal.Title>
          </Modal.Header>
          <Modal.Body style={modalSectionStyle}>
            {executeSkill?.inputs?.length > 0 ? (
              executeSkill.inputs.map(inp => (
                <Form.Group key={inp.name} className="mb-3">
                  <Form.Label style={{ fontSize: '0.85rem', color: 'var(--color-foreground)' }}>
                    {inp.name}{inp.required && <span className="text-danger ms-1">*</span>}
                    {inp.description && <span className="text-muted ms-2" style={{ fontSize: '0.75rem' }}> - {inp.description}</span>}
                  </Form.Label>
                  <Form.Control type="text" placeholder={`${t('execute.inputValue')}...`} value={executeInputs[inp.name] || ''} onChange={e => setExecuteInputs({ ...executeInputs, [inp.name]: e.target.value })} style={inputStyle} />
                </Form.Group>
              ))
            ) : (
              <p className="text-muted">{t('noSkillsDesc')}</p>
            )}
            {executeResult && (
              <div className="mt-3">
                <Alert variant={executeResult.success ? 'success' : 'danger'}><strong>{executeResult.success ? t('execute.success') : t('execute.error')}</strong></Alert>
                {executeResult.data && (
                  <pre style={{ background: 'rgba(0,0,0,0.3)', color: '#e2e8f0', padding: '1rem', borderRadius: 8, fontSize: '0.82rem', maxHeight: 300, overflow: 'auto' }}>
                    {JSON.stringify(executeResult.data, null, 2)}
                  </pre>
                )}
                {executeResult.error && typeof executeResult.error === 'string' && (
                  <pre style={{ background: 'rgba(220,53,69,0.1)', color: '#f87171', padding: '1rem', borderRadius: 8, fontSize: '0.82rem' }}>{executeResult.error}</pre>
                )}
              </div>
            )}
          </Modal.Body>
          <Modal.Footer style={{ ...modalSectionStyle, borderTop: '1px solid var(--color-border)' }}>
            <Button variant="outline-secondary" onClick={() => { setExecuteSkill(null); setExecuteResult(null); }} style={{ borderRadius: 8 }}>{t('close')}</Button>
            <Button variant="primary" onClick={handleExecute} disabled={executing} style={{ borderRadius: 8 }}>
              {executing ? <><Spinner animation="border" size="sm" className="me-2" style={{ width: 14, height: 14, borderWidth: 1.5 }} />{t('running')}</> : <><FaPlay className="me-2" size={10} />{t('execute.submit')}</>}
            </Button>
          </Modal.Footer>
        </Modal>

        {/* ── Create / Edit Modal ── */}
        <Modal show={showCreate} onHide={() => setShowCreate(false)} size="lg" centered>
          <Modal.Header closeButton style={{ ...modalSectionStyle, borderBottom: '1px solid var(--color-border)' }}>
            <Modal.Title style={{ fontSize: '1.1rem' }}>
              {editSkill ? <><FaEdit className="me-2" size={14} />{t('actions.edit')}</> : <><FaPlus className="me-2" size={14} />{t('createSkill')}</>}
            </Modal.Title>
          </Modal.Header>
          <Modal.Body style={modalSectionStyle}>
            <Row>
              <Col md={6}>
                <Form.Group className="mb-3">
                  <Form.Label style={{ fontSize: '0.85rem', color: 'var(--color-foreground)' }}>{t('form.name')} <span className="text-danger">*</span></Form.Label>
                  <Form.Control type="text" placeholder={t('form.namePlaceholder')} value={newSkill.name} onChange={e => setNewSkill({ ...newSkill, name: e.target.value })} style={inputStyle} />
                </Form.Group>
              </Col>
              <Col md={3}>
                <Form.Group className="mb-3">
                  <Form.Label style={{ fontSize: '0.85rem', color: 'var(--color-foreground)' }}>{t('form.engine')}</Form.Label>
                  <div className="d-flex gap-2 mt-1">
                    {['python', 'shell', 'markdown'].map(eng => {
                      const Icon = ENGINE_ICONS[eng];
                      return (
                        <div
                          key={eng}
                          role="button"
                          onClick={() => setNewSkill({ ...newSkill, engine: eng, script: newSkill.script === ENGINE_DEFAULTS[newSkill.engine] ? ENGINE_DEFAULTS[eng] : newSkill.script })}
                          style={{
                            padding: '6px 10px', borderRadius: 8, cursor: 'pointer', textAlign: 'center', fontSize: '0.72rem', fontWeight: 500,
                            background: newSkill.engine === eng ? 'var(--color-primary, #6366f1)' : 'rgba(255,255,255,0.05)',
                            color: newSkill.engine === eng ? '#fff' : 'var(--color-foreground-muted)',
                            border: `1px solid ${newSkill.engine === eng ? 'transparent' : 'rgba(255,255,255,0.1)'}`,
                          }}
                        >
                          <Icon size={14} className="d-block mx-auto mb-1" />
                          {eng.charAt(0).toUpperCase() + eng.slice(1)}
                        </div>
                      );
                    })}
                  </div>
                </Form.Group>
              </Col>
              <Col md={3}>
                <Form.Group className="mb-3">
                  <Form.Label style={{ fontSize: '0.85rem', color: 'var(--color-foreground)' }}>{t('form.category')}</Form.Label>
                  <Form.Select value={newSkill.category} onChange={e => setNewSkill({ ...newSkill, category: e.target.value })} style={inputStyle}>
                    {CATEGORIES.filter(c => c !== 'all').map(c => <option key={c} value={c}>{t(`categories.${c}`)}</option>)}
                  </Form.Select>
                </Form.Group>
              </Col>
            </Row>

            <Form.Group className="mb-3">
              <Form.Label style={{ fontSize: '0.85rem', color: 'var(--color-foreground)' }}>{t('form.description')}</Form.Label>
              <Form.Control as="textarea" rows={2} placeholder={t('form.descriptionPlaceholder')} value={newSkill.description} onChange={e => setNewSkill({ ...newSkill, description: e.target.value })} style={inputStyle} />
            </Form.Group>

            <Row>
              <Col md={6}>
                <Form.Group className="mb-3">
                  <Form.Label style={{ fontSize: '0.85rem', color: 'var(--color-foreground)' }}>{t('form.autoTrigger')}</Form.Label>
                  <Form.Control type="text" placeholder={t('form.autoTriggerPlaceholder')} value={newSkill.auto_trigger} onChange={e => setNewSkill({ ...newSkill, auto_trigger: e.target.value })} style={inputStyle} />
                </Form.Group>
              </Col>
              <Col md={6}>
                <Form.Group className="mb-3">
                  <Form.Label style={{ fontSize: '0.85rem', color: 'var(--color-foreground)' }}>{t('form.tags')}</Form.Label>
                  <Form.Control type="text" placeholder={t('form.tagsPlaceholder')} value={newSkill.tags} onChange={e => setNewSkill({ ...newSkill, tags: e.target.value })} style={inputStyle} />
                </Form.Group>
              </Col>
            </Row>

            <Form.Group className="mb-3">
              <Form.Label style={{ fontSize: '0.85rem', color: 'var(--color-foreground)' }}>{t('form.chainTo')}</Form.Label>
              <Form.Select multiple value={newSkill.chain_to} onChange={e => setNewSkill({ ...newSkill, chain_to: Array.from(e.target.selectedOptions, o => o.value) })} style={{ ...inputStyle, minHeight: 60 }}>
                {skills.filter(s => s.slug !== editSkill?.slug).map(s => <option key={s.slug} value={s.slug}>{s.name}</option>)}
              </Form.Select>
              <Form.Text className="text-muted" style={{ fontSize: '0.72rem' }}>{t('form.chainToPlaceholder')}</Form.Text>
            </Form.Group>

            {/* Inputs builder */}
            <div className="mb-3">
              <div className="d-flex align-items-center justify-content-between mb-2">
                <Form.Label className="mb-0" style={{ fontSize: '0.85rem', color: 'var(--color-foreground)' }}>{t('form.inputsSection')}</Form.Label>
                <Button variant="outline-primary" size="sm" onClick={handleAddInput} style={{ borderRadius: 6, fontSize: '0.78rem' }}><FaPlus className="me-1" size={10} />{t('form.addInput')}</Button>
              </div>
              {newSkill.inputs.map((inp, i) => (
                <div key={i} className="d-flex align-items-center gap-2 mb-2 p-2" style={{ background: 'rgba(100,130,170,0.05)', borderRadius: 8, border: '1px solid var(--color-border)' }}>
                  <Form.Control size="sm" placeholder={t('form.inputName')} value={inp.name} onChange={e => handleInputChange(i, 'name', e.target.value)} style={{ ...inputStyle, borderRadius: 6, flex: '0 0 130px' }} />
                  <Form.Select size="sm" value={inp.type} onChange={e => handleInputChange(i, 'type', e.target.value)} style={{ ...inputStyle, borderRadius: 6, flex: '0 0 90px' }}>
                    <option value="string">string</option>
                    <option value="number">number</option>
                    <option value="boolean">boolean</option>
                  </Form.Select>
                  <Form.Control size="sm" placeholder={t('form.inputDescription')} value={inp.description} onChange={e => handleInputChange(i, 'description', e.target.value)} style={{ ...inputStyle, borderRadius: 6, flex: 1 }} />
                  <Form.Check type="switch" label={t('form.inputRequired')} checked={inp.required} onChange={e => handleInputChange(i, 'required', e.target.checked)} style={{ fontSize: '0.72rem', whiteSpace: 'nowrap' }} />
                  <Button variant="outline-danger" size="sm" onClick={() => handleRemoveInput(i)} style={{ borderRadius: 6, padding: '2px 8px' }}><FaTimes size={10} /></Button>
                </div>
              ))}
            </div>

            {/* Script */}
            <Form.Group className="mb-3">
              <Form.Label style={{ fontSize: '0.85rem', color: 'var(--color-foreground)' }}>{t('form.scriptContent')}</Form.Label>
              <Form.Control as="textarea" rows={10} value={newSkill.script} onChange={e => setNewSkill({ ...newSkill, script: e.target.value })} style={{ background: 'rgba(0,0,0,0.3)', border: `1px solid ${formErrors.script ? 'var(--bs-danger)' : 'var(--color-border)'}`, color: '#e2e8f0', borderRadius: 8, fontFamily: 'monospace', fontSize: '0.82rem', lineHeight: 1.6 }} />
              {formErrors.script && (
                <div className="mt-1" style={{ fontSize: '0.78rem', color: 'var(--bs-danger)' }}>
                  <FaExclamationTriangle className="me-1" size={10} />{formErrors.script}
                </div>
              )}
            </Form.Group>
            {formErrors.name && (
              <Alert variant="danger" className="py-2" style={{ fontSize: '0.82rem' }}>
                <FaExclamationTriangle className="me-1" size={12} />{formErrors.name}
              </Alert>
            )}
          </Modal.Body>
          <Modal.Footer style={{ ...modalSectionStyle, borderTop: '1px solid var(--color-border)' }}>
            <Button variant="outline-secondary" onClick={() => setShowCreate(false)} style={{ borderRadius: 8 }}>{t('cancel')}</Button>
            <Button variant="primary" onClick={handleSaveSkill} disabled={creating || !newSkill.name.trim()} style={{ borderRadius: 8 }}>
              {creating ? <><Spinner animation="border" size="sm" className="me-2" style={{ width: 14, height: 14, borderWidth: 1.5 }} />{t('creating')}</> : <><FaPlus className="me-2" size={10} />{editSkill ? t('actions.edit') : t('create')}</>}
            </Button>
          </Modal.Footer>
        </Modal>

        {/* ── MCP Connect Modal ── */}
        <Modal show={showMcpConnect} onHide={() => setShowMcpConnect(false)} size="lg" centered>
          <Modal.Header closeButton style={{ ...modalSectionStyle, borderBottom: '1px solid var(--color-border)' }}>
            <Modal.Title style={{ fontSize: '1.1rem' }}><FaPlug className="me-2" size={16} />{t('mcp.connectExternal')}</Modal.Title>
          </Modal.Header>
          <Modal.Body style={modalSectionStyle}>
            <p className="text-muted small mb-3">{t('mcp.intro')}</p>

            {mcpLoading ? (
              <div className="text-center py-3"><Spinner animation="border" size="sm" /></div>
            ) : (
              <>
                {/* Server URL */}
                <div className="mb-3">
                  <Form.Label style={{ fontSize: '0.82rem', color: 'var(--color-foreground)' }}>{t('mcp.serverUrl')}</Form.Label>
                  <InputGroup>
                    <Form.Control readOnly value={mcpServerUrl} style={inputStyle} />
                    <Button variant="outline-secondary" onClick={() => copyToClipboard(mcpServerUrl, 'url')}>
                      {copied === 'url' ? '✓' : <FaCopy size={12} />}
                    </Button>
                  </InputGroup>
                </div>

                {/* Tool count + manifest peek */}
                {mcpManifest && (
                  <Alert variant="info" className="py-2" style={{ fontSize: '0.82rem' }}>
                    {t('mcp.toolsAvailable', { count: (mcpManifest.tools || []).length })}
                  </Alert>
                )}

                {/* Warn if the user isn't logged in — auth token placeholder is useless */}
                {!storedUser?.access_token && (
                  <Alert variant="warning" className="py-2" style={{ fontSize: '0.78rem' }}>
                    {t('mcp.tokenMissing')}
                  </Alert>
                )}

                {/* Claude Code config */}
                {[
                  { key: 'claude', label: 'Claude Code', path: '~/.claude/mcp.json' },
                  { key: 'gemini', label: 'Gemini CLI', path: '~/.gemini/config.json' },
                  { key: 'copilot', label: 'VS Code Copilot', path: 'settings.json' },
                ].map(({ key, label, path }) => {
                  const serialized = JSON.stringify(mcpConfigs[key], null, 2);
                  return (
                    <div key={key} className="mb-3">
                      <Form.Label style={{ fontSize: '0.82rem', color: 'var(--color-foreground)' }}>
                        {label} — <code style={{ fontSize: '0.78rem' }}>{path}</code>
                      </Form.Label>
                      <div style={{ position: 'relative' }}>
                        <pre style={{ background: 'rgba(0,0,0,0.3)', color: '#e2e8f0', padding: '0.75rem', borderRadius: 8, fontSize: '0.78rem', margin: 0, overflow: 'auto' }}>
                          {serialized}
                        </pre>
                        <Button
                          variant="outline-secondary" size="sm"
                          style={{ position: 'absolute', top: 6, right: 6, padding: '2px 6px' }}
                          onClick={() => copyToClipboard(serialized, key)}
                        >
                          {copied === key ? '✓' : <FaCopy size={11} />}
                        </Button>
                      </div>
                    </div>
                  );
                })}

                <Alert variant="secondary" className="py-2 mb-0" style={{ fontSize: '0.78rem' }}>
                  {t('mcp.authNote')}
                </Alert>
              </>
            )}
          </Modal.Body>
          <Modal.Footer style={{ ...modalSectionStyle, borderTop: '1px solid var(--color-border)' }}>
            <Button variant="outline-secondary" onClick={() => setShowMcpConnect(false)} style={{ borderRadius: 8 }}>{t('close')}</Button>
          </Modal.Footer>
        </Modal>

        {/* ── GitHub Import Modal ── */}
        <Modal show={showImport} onHide={() => setShowImport(false)} centered>
          <Modal.Header closeButton style={{ ...modalSectionStyle, borderBottom: '1px solid var(--color-border)' }}>
            <Modal.Title style={{ fontSize: '1.1rem' }}><FaGithub className="me-2" size={18} />{t('actions.import')}</Modal.Title>
          </Modal.Header>
          <Modal.Body style={modalSectionStyle}>
            <p className="text-muted small mb-3">Paste a GitHub repo URL containing skill directories (each with a <code>skill.md</code> file).</p>
            <Form.Group>
              <Form.Label style={{ fontSize: '0.85rem', color: 'var(--color-foreground)' }}>Repository URL</Form.Label>
              <Form.Control type="text" placeholder="https://github.com/owner/repo or owner/repo/path/to/skills" value={importUrl} onChange={e => setImportUrl(e.target.value)} style={inputStyle} />
              <Form.Text className="text-muted" style={{ fontSize: '0.75rem' }}>Supports: full URLs, <code>owner/repo</code>, or <code>owner/repo/path/to/skill</code></Form.Text>
            </Form.Group>
          </Modal.Body>
          <Modal.Footer style={{ ...modalSectionStyle, borderTop: '1px solid var(--color-border)' }}>
            <Button variant="outline-secondary" onClick={() => setShowImport(false)} style={{ borderRadius: 8 }}>{t('cancel')}</Button>
            <Button variant="primary" onClick={handleImportGithub} disabled={importing || !importUrl.trim()} style={{ borderRadius: 8 }}>
              {importing ? <><Spinner animation="border" size="sm" className="me-2" style={{ width: 14, height: 14, borderWidth: 1.5 }} />Importing...</> : <><FaGithub className="me-2" size={14} />Import</>}
            </Button>
          </Modal.Footer>
        </Modal>
      </div>
    </Layout>
  );
};

export default SkillsPage;
